#include "xc.inc"
    
GLOBAL _isprime

PSECT mytext, local, class=CODE, reloc=2
 
 
 _isprime:
    clrf TRISA
    clrf TRISB
    movlw 0x36
    movwf TRISB
    movlw 0x02
    movff 0x001, TRISA
    cpfseq TRISA
        decf TRISB
    movlw 0x03
    cpfseq TRISA
        decf TRISB
    movlw 0x05
    cpfseq TRISA
        decf TRISB
    movlw 0x07
    cpfseq TRISA
        decf TRISB
    movlw 0x0B
    cpfseq TRISA
        decf TRISB
    movlw 0x0D
    cpfseq TRISA
        decf TRISB
    movlw 0x11
    cpfseq TRISA
        decf TRISB
    movlw 0x13
    cpfseq TRISA
        decf TRISB
    movlw 0x17
    cpfseq TRISA
        decf TRISB
    movlw 0x1D
    cpfseq TRISA
        decf TRISB
    movlw 0x1F
    cpfseq TRISA
        decf TRISB
    movlw 0x25
    cpfseq TRISA
        decf TRISB
    movlw 0x29
    cpfseq TRISA
        decf TRISB
    movlw 0x2B
    cpfseq TRISA
        decf TRISB
    movlw 0x2F
    cpfseq TRISA
        decf TRISB
    movlw 0x35
    cpfseq TRISA
        decf TRISB
    movlw 0x3B
    cpfseq TRISA
        decf TRISB
    movlw 0x3D
    cpfseq TRISA
        decf TRISB
    movlw 0x43
    cpfseq TRISA
        decf TRISB
    movlw 0x47
    cpfseq TRISA
        decf TRISB
    movlw 0x49
    cpfseq TRISA
        decf TRISB
    movlw 0x4F
    cpfseq TRISA
        decf TRISB
    movlw 0x53
    cpfseq TRISA
        decf TRISB
    movlw 0x59
    cpfseq TRISA
        decf TRISB
    movlw 0x61
    cpfseq TRISA
        decf TRISB
    movlw 0x65
    cpfseq TRISA
        decf TRISB
    movlw 0x67
    cpfseq TRISA
        decf TRISB
    movlw 0x6B
    cpfseq TRISA
        decf TRISB
    movlw 0x6D
    cpfseq TRISA
        decf TRISB
    movlw 0x71
    cpfseq TRISA
        decf TRISB
    movlw 0x7F
    cpfseq TRISA
        decf TRISB
    movlw 0x83
    cpfseq TRISA
        decf TRISB
    movlw 0x89
    cpfseq TRISA
        decf TRISB
    movlw 0x8B
    cpfseq TRISA
        decf TRISB
    movlw 0x95
    cpfseq TRISA
        decf TRISB
    movlw 0x97
    cpfseq TRISA
        decf TRISB
    movlw 0x9D
    cpfseq TRISA
        decf TRISB
    movlw 0xA3
    cpfseq TRISA
        decf TRISB
    movlw 0xA7
    cpfseq TRISA
        decf TRISB
    movlw 0xAD
    cpfseq TRISA
        decf TRISB
    movlw 0xB3
    cpfseq TRISA
        decf TRISB
    movlw 0xB5
    cpfseq TRISA
        decf TRISB
    movlw 0xBF
    cpfseq TRISA
        decf TRISB
    movlw 0xC1
    cpfseq TRISA
        decf TRISB
    movlw 0xC5
    cpfseq TRISA
        decf TRISB
    movlw 0xC7
    cpfseq TRISA
        decf TRISB
    movlw 0xD3
    cpfseq TRISA
        decf TRISB
    movlw 0xDF
    cpfseq TRISA
        decf TRISB
    movlw 0xE3
    cpfseq TRISA
        decf TRISB
    movlw 0xE5
    cpfseq TRISA
        decf TRISB
    movlw 0xE9
    cpfseq TRISA
        decf TRISB
    movlw 0xEF
    cpfseq TRISA
        decf TRISB
    movlw 0xF1
    cpfseq TRISA
        decf TRISB
    movlw 0xFB
    cpfseq TRISA
        decf TRISB
	
	

    clrf WREG
    movlw 0xFF
    tstfsz TRISB
	movlw 0x01
    movwf 0x001
    return
